CREATE TABLE [dbo].[Account](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Agreed] [int] NOT NULL,
	[PolicyTypeId] [int] NOT NULL,
	[OwnerId] [int] NOT NULL,
	[PaymentNumber] [int] NOT NULL,
	[BusinessTrip] BIT NOT NULL,
	[File] NVARCHAR(500) NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
