CREATE TABLE [dbo].[dtpFile](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DtpId] [int] NOT NULL,
	[Name] NVARCHAR(100) NULL,
	[File] NVARCHAR(300) NOT NULL,
 CONSTRAINT [PK_dtpFile] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[dtpFile]  WITH CHECK ADD  CONSTRAINT [FK_dtpFile_DTP] FOREIGN KEY([DtpId])
REFERENCES [dbo].[DTP] ([dtp_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[dtpFile] CHECK CONSTRAINT [FK_dtpFile_DTP]
GO
