CREATE TABLE [dbo].[EmployeesName](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
 CONSTRAINT [PK_employeesName] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
