CREATE TABLE [dbo].[Employees](
	[RegionId] [int] NOT NULL,
	[EmployeesNameId] [int] NOT NULL,
	[DriverId] [int] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[RegionId] ASC,
	[EmployeesNameId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
