CREATE TABLE [dbo].[FuelCardDriver](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FuelCardId] [int] NOT NULL,
	[DriverId] [int] NOT NULL,
	[DateBegin] [datetime] NOT NULL,
	[DateEnd] [datetime] NULL,
 CONSTRAINT [PK_FuelCardDriver] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
