CREATE TABLE [dbo].[Fuel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[fuelCardId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Count] [float] NOT NULL,
	[EngineTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Fuel] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
