CREATE TABLE [dbo].[Instraction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Date] [datetime] NOT NULL,
	[DriverId] [int] NOT NULL,
	[File] NVARCHAR(100) NULL,
 CONSTRAINT [PK_Instraction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Instraction]  WITH CHECK ADD  CONSTRAINT [FK_Instraction_Driver] FOREIGN KEY([DriverId])
REFERENCES [dbo].[Driver] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Instraction] CHECK CONSTRAINT [FK_Instraction_Driver]
GO
