CREATE TABLE [dbo].[MainPoint](
	[PointId] [int] NOT NULL,
 CONSTRAINT [PK_MainPoint_1] PRIMARY KEY CLUSTERED 
(
	[PointId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MainPoint]  WITH CHECK ADD  CONSTRAINT [FK_MainPoint_Point] FOREIGN KEY([PointId])
REFERENCES [dbo].[MyPoint] ([Id])
GO

ALTER TABLE [dbo].[MainPoint] CHECK CONSTRAINT [FK_MainPoint_Point]
GO
