CREATE TABLE [dbo].[MedicalCert](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[DateBegin] [datetime] NOT NULL,
	[DateEnd] [datetime] NOT NULL,
	[DriverId] [int] NOT NULL,
	[File] NVARCHAR(500) NULL,
	[NotificationSent] bit NULL,
 CONSTRAINT [PK_MedicalCert] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MedicalCert]  WITH CHECK ADD  CONSTRAINT [FK_MedicalCert_Driver] FOREIGN KEY([DriverId])
REFERENCES [dbo].[Driver] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MedicalCert] CHECK CONSTRAINT [FK_MedicalCert_Driver]
GO
