CREATE TABLE [dbo].[Mileage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[carId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_mileage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mileage]  WITH CHECK ADD  CONSTRAINT [FK_Mileage_Car] FOREIGN KEY([carId])
REFERENCES [dbo].[Car] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Mileage] CHECK CONSTRAINT [FK_Mileage_Car]
GO
