CREATE TABLE [dbo].[Proxy](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Date] [datetime] NOT NULL,
	[ProxyTypeId] [int] NOT NULL,
	[DriverId] [int] NOT NULL,
	[CarId] [int] NOT NULL,
 CONSTRAINT [PK_Proxy] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Proxy]  WITH CHECK ADD  CONSTRAINT [FK_Proxy_Car] FOREIGN KEY([CarId])
REFERENCES [dbo].[Car] ([Id])
GO

ALTER TABLE [dbo].[Proxy] CHECK CONSTRAINT [FK_Proxy_Car]
GO

ALTER TABLE [dbo].[Proxy]  WITH CHECK ADD  CONSTRAINT [FK_Proxy_Driver] FOREIGN KEY([DriverId])
REFERENCES [dbo].[Driver] ([Id])
GO

ALTER TABLE [dbo].[Proxy] CHECK CONSTRAINT [FK_Proxy_Driver]
GO

ALTER TABLE [dbo].[Proxy]  WITH CHECK ADD  CONSTRAINT [FK_Proxy_proxyType] FOREIGN KEY([ProxyTypeId])
REFERENCES [dbo].[proxyType] ([Id])
GO

ALTER TABLE [dbo].[Proxy] CHECK CONSTRAINT [FK_Proxy_proxyType]
GO
