CREATE TABLE [dbo].[PTS](
	[CarId] [int] NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Date] [datetime] NOT NULL,
	[GiveOrg] NVARCHAR(100) NULL,
	[File] NVARCHAR(200) NULL,
 CONSTRAINT [PK_PTS] PRIMARY KEY CLUSTERED 
(
	[CarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PTS]  WITH CHECK ADD  CONSTRAINT [FK_PTS_Car] FOREIGN KEY([CarId])
REFERENCES [dbo].[Car] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PTS] CHECK CONSTRAINT [FK_PTS_Car]
GO
