CREATE TABLE [dbo].[Route](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MypointId1] [int] NOT NULL,
	[MypointId2] [int] NOT NULL,
	[Distance] [int] NOT NULL,
 CONSTRAINT [PK_Route] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Route]  WITH CHECK ADD  CONSTRAINT [FK_Route_Point] FOREIGN KEY([MypointId1])
REFERENCES [dbo].[MyPoint] ([Id])
GO

ALTER TABLE [dbo].[Route] CHECK CONSTRAINT [FK_Route_Point]
GO

ALTER TABLE [dbo].[Route]  WITH CHECK ADD  CONSTRAINT [FK_Route_Point1] FOREIGN KEY([MypointId2])
REFERENCES [dbo].[MyPoint] ([Id])
GO

ALTER TABLE [dbo].[Route] CHECK CONSTRAINT [FK_Route_Point1]
GO
