CREATE TABLE [dbo].[CarSale](
	[CarId] [int] NOT NULL,
	[Date] [datetime] NULL,
	[Comment] NVARCHAR(100) NULL,
 CONSTRAINT [PK_CarSale] PRIMARY KEY CLUSTERED 
(
	[CarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CarSale]  WITH CHECK ADD  CONSTRAINT [FK_CarSale_Car] FOREIGN KEY([CarId])
REFERENCES [dbo].[Car] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CarSale] CHECK CONSTRAINT [FK_CarSale_Car]
GO
