CREATE TABLE [dbo].[ShipPart](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CarId] [int] NOT NULL,
	[DriverId] [int] NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[DateRequest] [datetime] NULL,
	[DateSent] [datetime] NULL,
	[File] NVARCHAR(500) NULL,
 CONSTRAINT [PK_ShipParts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
