CREATE TABLE [dbo].[ssDTP](
	[MarkId] [int] NOT NULL,
	[ServiceStantionId] [int] NOT NULL,
 CONSTRAINT [PK_ssDTP_1] PRIMARY KEY CLUSTERED 
(
	[MarkId] ASC,
	[ServiceStantionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
