CREATE TABLE [dbo].[STS](
	[CarId] [int] NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Date] [datetime] NOT NULL,
	[GiveOrg] NVARCHAR(100) NULL,
	[File] NVARCHAR(200) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STS]  WITH CHECK ADD  CONSTRAINT [FK_STS_Car] FOREIGN KEY([CarId])
REFERENCES [dbo].[Car] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[STS] CHECK CONSTRAINT [FK_STS_Car]
GO
