CREATE TABLE [dbo].[WayBillRoute](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[WayBillDayId] [int] NOT NULL,
	[MyPointId1] [int] NOT NULL,
	[MyPointId2] [int] NOT NULL,
	[Distance] [int] NOT NULL,
 CONSTRAINT [PK_WayBillRoute] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
