//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить документ?.
        /// </summary>
        public static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить ДТП?.
        /// </summary>
        public static string DeleteDTP {
            get {
                return ResourceManager.GetString("DeleteDTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для работы с программой.
        /// </summary>
        public static string HaveNotRights {
            get {
                return ResourceManager.GetString("HaveNotRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля пробег не является числом.
        /// </summary>
        public static string MileageIsNotValid {
            get {
                return ResourceManager.GetString("MileageIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля пробег не должно превышать 1000000 км.
        /// </summary>
        public static string MileageMoreThan1000000 {
            get {
                return ResourceManager.GetString("MileageMoreThan1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить информацию о пробеге?.
        /// </summary>
        public static string NeedDeleteMileage {
            get {
                return ResourceManager.GetString("NeedDeleteMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сохранения необходимо выбрать комплектацию.
        /// </summary>
        public static string NeedSelectGrade {
            get {
                return ResourceManager.GetString("NeedSelectGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить письмо. Нет ответа от сервера. Попытайтесь отправить через некоторое время.
        /// </summary>
        public static string NoAnswerFromMailServer {
            get {
                return ResourceManager.GetString("NoAnswerFromMailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед действием необходимо выделить запись в таблице.
        /// </summary>
        public static string SelectRowBeforeAction {
            get {
                return ResourceManager.GetString("SelectRowBeforeAction", resourceCulture);
            }
        }
    }
}
